export enum genres {
  'Islamic',
  'Science Fiction',
  'Mystery/Thriller',
  'Horror',
  'Fantasy',
  'Historical Fiction',
  'Biography/Autobiography',
  'Memoir',
  'Self-Help',
  'Travel',
  'Cookbooks',
  'Romance',
  'Business/Finance',
  'Science/Technology',
  'Art/Photography',
  "Children's Books",
  'Young Adult',
  'Comics/Graphic Novels',
  'Poetry',
  'Drama',
  'Philosophy',
  'Detective',
}
